### ISSUE TITLE
Verify openfec is building in release mode

### ISSUE THREAD

**Issue by digital-nomad8620** [oresat/oresat-libdxwifi#16]
The CMake file shipped with Openfec (`openfec/CMakelists.txt`) does a lot of weird stuff and I'm not actually sure it's building the library with release optimizations turned on. They use a bunch of unnecessary string comparisons to test if it's a debug build or not. I'm opening this issue to either: A) Remind myself to check for the `o3` flag when openfec is compiled or B) have someone else do it .

**Comment by khanu263** [comment]
@AlexanderJDupree Just looked into this and I'm pretty sure it is in release mode...in `openfec/CMakeLists.txt`

```
# Release mode
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_C_FLAGS "-O4")
```

And then all the compilation commands seem to have that flag when you do `make VERBOSE=1`

```
...
Scanning dependencies of target openfec
make[2]: Leaving directory '/home/ukhan/github/oresat-dxwifi-software/build'
make -f openfec/src/CMakeFiles/openfec.dir/build.make openfec/src/CMakeFiles/openfec.dir/build
make[2]: Entering directory '/home/ukhan/github/oresat-dxwifi-software/build'
[ 13%] Building C object openfec/src/CMakeFiles/openfec.dir/lib_advanced/ldpc_from_file/of_ldpc_ff_api.c.o
... /usr/bin/cc -DDXWIFI_VERSION=\"0.1.0-0-Debug\" ... -O4 -O3 -DNDEBUG ...
...
```

So I think this verifies it? Feel free to close the issue if it does, or not if it doesn't.

**Comment by digital-nomad8620** [comment]
@khanu263 nope that's good enough for me! Thanks for that!.
