### ISSUE TITLE
Target Defaults for Encode / Decode to stdin

### ISSUE THREAD

**Issue by ghost** [oresat/oresat-libdxwifi#24]
Assuming that encode / decode are called without an input file, the program currently returns an error.

Setting the default target to stdin for both may be a decent fix.  Alternatively, improving the error message so that the end user can tell that enc/dec require an input file would be another alternative.

**Comment by digital-nomad8620** [comment]
See #25

**Comment by digital-nomad8620** [comment]
@CD-W if we do #25 then there won't be an error message and excluding the input file is a use case instead of a bug. We should however make it clear in the program doc string in `encode/cli.c` that you can choose to read bytes form `stdin` or from an input file.

**Comment by digital-nomad8620** [comment]
@khanu263 should we close this issue since we've opened #28? Also, this issue would be addressed in #25 anyways.

**Comment by khanu263** [comment]
Yep, I agree, this will be addressed in other issues at this point...
