### ISSUE TITLE
Implement `encode_stream` functions in `encode.c` and `decode.c`

### ISSUE THREAD

**Issue by digital-nomad8620** [oresat/oresat-libdxwifi#25]
Currently the `encode` and `decode` programs simply panic when the user omits an input file. This is because the programs were designed to be able to read bytes form `stdin` and then FEC encode and write those bytes out. However, this functionality has not been implemented yet. 

The likely implementation for this is probably something along these lines:

1. Create a buffer of size X * FEC_SYMBOL_SIZE. (Making it evenly divisible by FEC_SYMBOL_SIZE ensures we won't get extra padding)
2.  Poll `stdin` for data and read it into the buffer. 
3.  Loop until the buffer is full
4.  If the buffer is full then FEC encode the entire buffer, and write out the encoded data. 
5.  Reset write pointer to beginning of the buffer and start from step 2. 

Since the loop could continue forever we will probably want to install a `sigint` handler to perform cleanup after the user kills the program.

**Comment by digital-nomad8620** [comment]
With the opening of #28 , this issue now looks a bit different. We can still implement the encode stream functions in `encode.c` and `decode.c` however we will want to add it `tx.c` and `rx.c` as well.

**Comment by khanu263** [comment]
I think we'll keep this issue around for now, but I'm going to make it lower priority for the time being.

**Comment by khanu263** [comment]
Actually, with the closing of #28, I'm going to go ahead and close this as well. We can reopen if we want but I think we should focus on doing everything through `tx` and `rx`.
