### ISSUE TITLE
RS Decoder isn't correcting for bit errors

### ISSUE THREAD

**Issue by digital-nomad8620** [oresat/oresat-libdxwifi#36]
After finally getting some time to more thoroughly test the `decoder` it appears that the Reed Solomon portion of the process is not actually correcting for any bit errors. I was suspicious of this when I handed off the FEC but I wasn't able to validate it until now. This is causing all the CRC checks to fail which causes the decoder to abort since it isn't able to find any valid OTI header. 

Here is a hexdump of the before and after we Reed Solomon decode a packet whose symbol data was all zeroes: 

![fec-error](https://user-images.githubusercontent.com/32920575/118743184-b3282800-b806-11eb-9c52-96450c8a0d6a.png)
 
The first 16 bytes highlighted in blue is the OTI header, which is actually in perfect condition. The bytes highlighted in purple are those with bit errors, there are 7 errors which RS should be able to correct for. The 7 bytes highlighted in green are the parity bits that we attached when we RS encoded the original symbol. 

As you can see after we RS decode the packet and consume the parity bits, the errors are still present. 

Unsure how to proceed, my guess is that this an issue of not using the RSCode library correctly. The library was sparsely documented and only had a minimal example. So, we may be missing some sort of initialization or parameters for the decoding routine.

**Comment by Cam57** [comment]
So I was looking around in fec.c and fec.h and notice that we don't call the initialize_ecc (); to initialize the ECC library. I am not sure where the best location for the function call would be but this might be the source of the problem. Here is the reference code I am using. [http://rscode.sourceforge.net/example.txt](url)
