### ISSUE TITLE
Create packages

### ISSUE THREAD

**Issue by nrwahl2** [oresat/oresat-libdxwifi#65]
Bundle all necessary onboard components for `libdxwifi` and `oresat-live-software` (camera and web server) into one or more .deb and/or Python packages. The packages should handle the entire installation onto an OreSat board (or BeagleBone Black test board) in one step.

All Python projects needs to have Python packages (and upload to PyPi) and non-Python projects need to have Debian packages.

**Comment by sashetov** [comment]
for capture package:
https://github.com/oresat/oresat-live-software/pull/18

**Comment by sashetov** [comment]
I just tested all the build procedures on my beaglebone test host and there is no issue with building it using current PR revision [e1b25b150307f89d32f8aaee743debbbf3f71868](https://github.com/oresat/oresat-live-software/commit/e1b25b150307f89d32f8aaee743debbbf3f71868)

**Comment by sashetov** [comment]
new PR with fixes implemented, also tested on BBB
https://github.com/oresat/oresat-live-software/pull/19

**Comment by sashetov** [comment]
PR for build script for server package. Tested on RPI
https://github.com/oresat/oresat-live-software/pull/20

**Comment by ryanpdx** [comment]
Done
