### ISSUE TITLE
Create custom image for OreSat

### ISSUE THREAD

**Issue by nrwahl2** [oresat/oresat-libdxwifi#66]
The image should contain everything that is required to run the OreSat Live mission (consider `oresat-libdxwifi`, `oresat-live-software`, `oresat-dxwifi-software`, etc.), without any unnecessary components. It should install the packages that are created in #65.

Make an attempt to verify which non-OreSat packages are actually required, and remove if unnecessary.

**Comment by ryanpdx** [comment]
This is mostly taken care of already with https://github.com/oresat/oresat-linux/tree/master/image_builder

**Comment by nrwahl2** [comment]
Ya love to see it.

**Comment by ryanpdx** [comment]
https://images.oresat.org/

**Comment by nrwahl2** [comment]
> https://images.oresat.org/

Right. From previous discussions about requirements, we thought we needed to create a new/different image with all of "our" stuff -- or perhaps update the `oresat-dxwifi` image accordingly.

**Comment by ryanpdx** [comment]
Done
